import torch


class SGLDReplayBuffer:
    """
    Replay buffer for Stochastic Gradient Langevin Dynamics (SGLD) sampler.
    Stores previous fake samples to initialize the MCMC chains, improving mixing
    and converging to the energy distribution faster.
    """

    def __init__(
        self,
        buffer_size: int,
        feature_dim: int,
        reinit_freq: float = 0.05,
        uniform_range: tuple = (-1.0, 1.0),
    ):
        """
        Initializes the replay buffer.

        Args:
            buffer_size (int): Maximum number of samples to store.
            feature_dim (int): Number of features per sample.
            reinit_freq (float): Probability of initializing a sample from uniform noise
                                 rather than the buffer (default: 5%).
            uniform_range (tuple): Range [min, max] for uniform noise initialization.
        """
        self.buffer_size = buffer_size
        self.feature_dim = feature_dim
        self.reinit_freq = reinit_freq
        self.uniform_range = uniform_range

        # Pre-allocate buffer tensor (default on CPU, should be updated based on use case)
        self.buffer = torch.empty(self.buffer_size, self.feature_dim)
        self.pointer = 0
        self.is_full = False

    def sample(self, batch_size: int) -> torch.Tensor:
        """
        Retrieves a batch of samples to initialize the SGLD chains.
        Following standard JEM practice, (1-reinit_freq) from buffer, reinit_freq from uniform noise.

        Args:
            batch_size (int): Number of samples to draw.

        Returns:
            torch.Tensor: Initial samples for SGLD of shape (batch_size, feature_dim).
        """
        # Generate full uniform noise batch initially
        noise_samples = torch.empty(batch_size, self.feature_dim).uniform_(
            *self.uniform_range
        )

        # If buffer is completely empty, return pure noise
        if self.pointer == 0 and not self.is_full:
            return noise_samples

        # Determine number of items to replace with buffer items
        num_reinit = max(1, int(batch_size * self.reinit_freq))
        num_buffer = batch_size - num_reinit

        max_idx = self.buffer_size if self.is_full else self.pointer

        # Pick random indices from the buffer
        buffer_indices = torch.randint(0, max_idx, (num_buffer,))
        buffer_samples = self.buffer[buffer_indices]

        # Combine noise samples (reinit) and buffer samples
        init_samples = torch.cat([noise_samples[:num_reinit], buffer_samples], dim=0)

        # Shuffle to mix noise and buffer samples
        shuffle_idx = torch.randperm(batch_size)
        return init_samples[shuffle_idx]

    def update(self, samples: torch.Tensor):
        """
        Updates the replay buffer with new samples generated by the SGLD loop.

        Args:
            samples (torch.Tensor): Fake samples to store, of shape (batch_size, feature_dim).
        """
        batch_size = samples.shape[0]

        # Make sure they are detached and on CPU (to avoid memory bloat)
        samples = samples.detach().cpu()

        # Calculate indices
        end_idx = self.pointer + batch_size

        if end_idx <= self.buffer_size:  # fits entirely
            self.buffer[self.pointer : end_idx] = samples
            self.pointer = end_idx
            if self.pointer == self.buffer_size:
                self.is_full = True
                self.pointer = 0
        else:  # wraps around
            overflow = end_idx - self.buffer_size
            items_to_fit = batch_size - overflow

            self.buffer[self.pointer : self.buffer_size] = samples[:items_to_fit]
            self.buffer[:overflow] = samples[items_to_fit:]

            self.pointer = overflow
            self.is_full = True
